import { LitElement, html, css } from "lit";

/**
 * Metro Pivot Item Component
 *
 * A child component for MetroPivot that represents a single tab panel.
 * Each PivotItem contains content that is displayed when its corresponding
 * tab header is selected in the parent Pivot component.
 *
 * Features:
 * - Header text attribute for the tab label
 * - Automatic active state management by parent Pivot
 * - Content padding and box-sizing for consistent layout
 * - Smooth opacity and scale transitions when becoming active
 *
 * Use as children of metro-pivot. Set the "header" attribute to define
 * the tab label text.
 *
 * @cssprop --metro-spacing-md - Medium spacing for content padding (default: 12px)
 *
 * @slot - Default slot for the pivot item content
 */
export class MetroPivotItem extends LitElement {
  static properties = {
    /**
     * Text displayed in the pivot tab header.
     * If not set, a default "Item N" label is generated by the parent.
     * @default ""
     */
    header: { type: String, reflect: true },
  };

  declare header: string;

  static styles = css`
    :host {
      display: block;
      padding: var(--metro-spacing-md, 12px);
      box-sizing: border-box;
    }
  `;

  constructor() {
    super();
    this.header = "";
  }

  render() {
    return html`<slot></slot>`;
  }
}

customElements.define("metro-pivot-item", MetroPivotItem);

declare global {
  interface HTMLElementTagNameMap {
    "metro-pivot-item": MetroPivotItem;
  }
}
